### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by plukevdh** [Ibsciss/ruby-middleware#12]
Can we get a new release on rubygems to include the latest kwargs changes in main?

**Comment by shtirlic** [comment]
+1, pls make new release to avoid git branch linking in Gemfile

**Comment by lulalala** [comment]
I've applied to be the maintainer and just pushed the new release. @shtirlic  @plukevdh if you can could you test it out please? Thanks.

**Comment by shtirlic** [comment]
@lulalala thank you, bundle updated to latest, looks fine.
