### ISSUE TITLE
Named parameters in middleware runner creation?

### ISSUE THREAD

**Issue by bramski** [Ibsciss/ruby-middleware#6]
Sure would be nice!

**Comment by lilobase** [comment]
Can you provide an example on how to use it (just to get an idea about the api you have in mind) ?

**Comment by bramski** [comment]
```
Middleware::Builder.new do |builder|
    builder.use MyMiddleware, named_arg1: 'foobar', named_arg2: 'deadbeef'
end
```

**Comment by bramski** [comment]
Should I make a PR?  Would you accept it?

**Comment by lilobase** [comment]
of course, with pleasure !

**Comment by bramski** [comment]
Actually... this just works.  Splat onto an array where the last element is hash with symbol keys will make them named arguments.
