### ISSUE TITLE
stack.replace doesnt work when you try and replace it with the same middleware

### ISSUE THREAD

**Issue by bramski** [Ibsciss/ruby-middleware#8]
I find we're often trying to change the arguments provided to one of our middlewares... but it doesn't work if I replace it.

```
stack.replace SomeMiddleware,
                        SomeMiddleware,
                         configuration: "different_config"
```
The new configuration is not applied :-(.

**Comment by lilobase** [comment]
I have found the bug, I will push a fix tomorrow

**Comment by lilobase** [comment]
I just push a fix : https://github.com/Ibsciss/ruby-middleware/commit/51bb6504737b126fcfb9c4845a806244fad3493b
