### ISSUE TITLE
Updates and help maintaining?

### ISSUE THREAD

**Issue by petems** [Ibsciss/ruby-middleware#9]
Hi @lilobase! I'm looking to move to this fork for my project as mitchell's original hasn't been updated for a while

Just looking through #7 #5 #8 and I can see there's been some movement last year around updating docs, fixing a bug and adding tags to the git repo... but there's not been any changes to the repo since 2015 still

Can I help? I don't want to end up forking again if I can help it 😄

**Comment by lilobase** [comment]
Thanks for the wake up call, I just fixed all opened issues ;)
Of course I'm always glad to receive help to improve this little project (documentation, PR, ...) !

**Comment by petems** [comment]
Awesome, glad to hear! 😄
